import{a as y,S as p,i as a}from"./assets/vendor-DnBR8w-b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function e(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=e(r);fetch(r.href,s)}})();const b="49692460-099fca5bd4b56e7d7d026f90d",L="https://pixabay.com/api/",w=y.create({baseURL:L,params:{key:b,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15}});async function m(t,o=1){return(await w.get("",{params:{q:t,page:o}})).data}const f=document.querySelector(".gallery"),S=new p(".gallery a");function g(t){const o=t.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${e.likes}</p>
        <p class="info-item"><b>Views:</b> ${e.views}</p>
        <p class="info-item"><b>Comments:</b> ${e.comments}</p>
        <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",o),S.refresh()}function v(){f.innerHTML=""}function q(){a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}function P(){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}function E(){const t=document.querySelector(".gallery").firstElementChild;if(t){const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}class R{constructor(){this.button=document.querySelector(".load-more")}show(){this.button.classList.remove("is-hidden")}hide(){this.button.classList.add("is-hidden")}}const c=new R,M=document.querySelector("#search-form");let i=1,u="",h=0;M.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements.searchQuery.value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}u=o,i=1,v(),c.hide(),document.querySelector(".loader").classList.remove("is-hidden");try{const{hits:e,totalHits:n}=await m(u,i);if(document.querySelector(".loader").classList.add("is-hidden"),e.length===0){P();return}g(e),t.target.elements.searchQuery.value="",h=Math.ceil(n/15),i<h&&c.show()}catch(e){document.querySelector(".loader").classList.add("is-hidden"),a.error({title:"Error",message:"Something went wrong. Please try again.",position:"topRight"}),console.error(e)}});function $(){return{currentPage:i,currentQuery:u,totalPages:h}}function O(){i+=1}const d=document.querySelector(".load-more-container .loader"),x=document.querySelector(".load-more");x.addEventListener("click",async()=>{c.hide(),d.classList.remove("is-hidden"),O();const{currentPage:t,currentQuery:o,totalPages:e}=$();try{const{hits:n}=await m(o,t);d.classList.add("is-hidden"),g(n),E(),t>=e?q():c.show()}catch(n){d.classList.add("is-hidden"),console.error(n)}});
//# sourceMappingURL=index.js.map
