import{a as y,S as g,i as a}from"./assets/vendor-DnBR8w-b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function e(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=e(r);fetch(r.href,s)}})();const p="49692460-099fca5bd4b56e7d7d026f90d",b="https://pixabay.com/api/",L=y.create({baseURL:b,params:{key:p,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15}});async function h(t,o=1){return(await L.get("",{params:{q:t,page:o}})).data}const m=document.querySelector(".gallery"),S=new g(".gallery a");function f(t){const o=t.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${e.likes}</p>
        <p class="info-item"><b>Views:</b> ${e.views}</p>
        <p class="info-item"><b>Comments:</b> ${e.comments}</p>
        <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",o),S.refresh()}function w(){m.innerHTML=""}function v(){a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}function q(){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}function P(){const t=document.querySelector(".gallery").firstElementChild;if(t){const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}class R{constructor(){this.button=document.querySelector(".load-more")}show(){this.button.classList.remove("is-hidden")}hide(){this.button.classList.add("is-hidden")}}const l=new R,E=document.querySelector("#search-form");let i=1,d="",u=0;E.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements.searchQuery.value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}d=o,i=1,w(),l.hide(),document.querySelector(".loader").classList.remove("is-hidden");try{const{hits:e,totalHits:n}=await h(d,i);if(document.querySelector(".loader").classList.add("is-hidden"),e.length===0){q();return}f(e),t.target.elements.searchQuery.value="",u=Math.ceil(n/15),i<u&&l.show()}catch(e){document.querySelector(".loader").classList.add("is-hidden"),a.error({title:"Error",message:"Something went wrong. Please try again.",position:"topRight"}),console.error(e)}});function M(){return{currentPage:i,currentQuery:d,totalPages:u}}function $(){i+=1}const O=document.querySelector(".load-more");O.addEventListener("click",async()=>{$();const{currentPage:t,currentQuery:o,totalPages:e}=M();document.querySelector(".loader").classList.remove("is-hidden");try{const{hits:n}=await h(o,t);document.querySelector(".loader").classList.add("is-hidden"),f(n),P(),t>=e&&(l.hide(),v())}catch(n){document.querySelector(".loader").classList.add("is-hidden"),console.error(n)}});
//# sourceMappingURL=index.js.map
